org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true


## Environment Properties

minecraft_version=26.2
forge_version=65.1.0


## Mod Properties

mod_id=imehotfix
mod_name=IME Hotfix
mod_license=LGPL-3.0-or-later
mod_version=1.2.0
mod_group_id=jp.antimeme.mc
mod_authors=Antimeme Productions
